all: part1 part2

test: test1 test2

part1:
	$(FUZION)/bin/fz part1.fz <input 71 1024

test1:
	$(FUZION)/bin/fz part1.fz <test_input 7 12

part2:
	$(FUZION)/bin/fz part2.fz <input 71 1024

test2:
	$(FUZION)/bin/fz part2.fz <test_input 7 12
