all: part1 part2

part1:
	$(FUZION)/bin/fz dec3_part1.fz <input

test1:
	$(FUZION)/bin/fz dec3_part1.fz <test_input

part2:
	$(FUZION)/bin/fz dec3_part2.fz <input

test2:
	$(FUZION)/bin/fz dec3_part2.fz <test_input
